config/routes.rb
Rails.application.routes.draw do
  devise_for :lots
  root 'orders#index'

  resources :lots do
    collection do
      get 'open_orders'
    end
  end
  resources :contacts do
    collection do
      post 'read'
      post 'unread'
      get 'faq'
    end
  end
  resources :accessories
  resources :zips
  resources :trees
  resources :available_trees
  resources :orders do
    collection do
      get 'zipcode_search'
      get 'order_confirmation'
      post 'order_claim'
      post 'order_release'
      post 'order_delivered'
      post 'confirm'
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :tree
  belongs_to :window
  has_many :accessory_orders
  has_many :accessories, through: :accessory_orders

  validates_presence_of :tree_id
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :address
  validates_presence_of :city
  validates_presence_of :zipcode
  validates_presence_of :state
  validates_presence_of :window_id
  validates :phone, length: { is: 10 }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

  def self.build_accessories(order, accessories)
    accessories.each do |a|
      if a != ""
        AccessoryOrder.create(order_id: order.id, accessory_id: a)
      end
    end
  end

  def self.available_trees(zip)
    lot_ids = Zip.where(code: zip).map(&:lot_id)
    lots = Lot.where(id: lot_ids)
    trees_ids = []
    lots.each do |lot|
      lot.available_trees.each do |tree|
        trees_ids << tree.tree_id
      end
    end
    trees_ids.uniq!
    trees = Tree.where(id: trees_ids).sort { |a,b| [a.type_id, a.price] <=> [b.type_id, b.price] }
    available_trees = []
    trees.each do |t|
      available_trees << ["#{t.height} ft. #{t.type.name} - $#{t.price.to_i}", t.id]
    end
    return available_trees, trees
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_lot!, only: [:order_claim, :order_release]

  def index
    @contact = Contact.new
  end

  def show
    @order = Order.find(params[:order_id])
    @accessories = @order.accessories
    @total = @accessories.empty? ? @order.tree.price : @order.tree.price + @accessories.inject(0){ |sum, a| sum + a.price }
  end

  def new
    @zip = params[:zip]
    @available_trees, @trees = Order.available_trees(@zip)
    if @zip.nil?
      flash[:notice] = "We need a zipcode!"
      redirect_to orders_path
    elsif @available_trees.empty?
      flash[:notice] = "Sorry we dont have any trees in that area!"
      redirect_to orders_path
    end
    @geo = Geokit::Geocoders::MultiGeocoder.geocode(@zip)
    if @geo.success
      @state = @geo.state
      @city = @geo.city
    end
    @order = Order.new
    @windows = Window.all
    @accessories = Accessory.all
    @contact = Contact.new
  end

  def confirm
    @order = Order.new(order_params)

    unless @order.valid?
      flash[:now] = "Order could not be processed!"
      @zip = @order.zipcode
      @state = @order.state
      @city = @order.city
      @available_trees, @trees = Order.available_trees(@zip)
      @windows = Window.all
      @accessories = Accessory.all
      params[:accessory_orders] = params[:order][:accessory_orders]
      render action: :new
    end
    @accessories = Accessory.where(id: params[:order][:accessory_orders])
    @total = @accessories.empty? ? @order.tree.price : @order.tree.price + @accessories.inject(0){ |sum, a| sum + a.price }
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      Order.build_accessories(@order, params[:accessory_orders])
      redirect_to order_confirmation_orders_path(id: @order.id)
    else
      flash[:now] = "Order could not be processed!"
      redirect_to orders_path
    end
  end

  def order_confirmation
    @order = Order.find(params[:id])
    @accessories = @order.accessories
    @total = @accessories.empty? ? @order.tree.price : @order.tree.price + @accessories.inject(0){ |sum, a| sum + a.price }
  end

  def order_claim
    @order = Order.find(params[:order_id])
    @order.lot_id = current_lot.id

    if @order.save
      flash[:notice] = "Order Claimed!"
      redirect_to open_orders_lots_path
    else
      flash[:notice] = "Order Claim Failed!"
      redirect_to open_orders_lots_path
    end
  end

  def order_release
    @order = Order.find(params[:order_id])
    @order.lot_id = nil

    if @order.save
      flash[:notice] = "Order Released!"
      redirect_to lot_path(current_lot.id)
    else
      flash[:notice] = "Order Release Failed!"
      redirect_to lot_path(current_lot.id)
    end
  end

  def order_delivered
    @order = Order.find(params[:order_id])
    @order.delivered = true

    if @order.save
      flash[:notice] = "Order Delivered!"
      redirect_to lot_path(current_lot.id)
    else
      flash[:notice] = "Order Delivered Failed!"
      redirect_to lot_path(current_lot.id)
    end
  end

  def zipcode_search
    @zip = params[:zipcode_search][:zipcode]

    @count = 0

    @zips = Zip.where(code: @zip).includes(:lot)

    @zips.each do |zip|
      @count += zip.lot.available_trees.count
    end

    if @zips.size > 0 && @count > 0
      redirect_to new_order_path(zip: @zip)
    else
      flash[:notice] = "Sorry we dont have any trees in that area!"
      redirect_to orders_path
    end
  end

  private

  def order_params
    params.require(:order).permit(:tree_id, :name, :email, :address, :city, :state,
                                  :zipcode, :lot_id, :window_id,
                                  :instructions, :phone, :order, :accessory_orders)
  end
end

app/views/orders/_balsam_fraser.html.erb
<div class="row background-green">
  <div class="container">
    <div class="row green">
      <div class="col-xs-12 col-sm-6">
        <div class='padding round-border background-white'>
          <%= image_tag 'balsam-fir.jpg', width: '100%' %>
          <br><br>
          <div class="tree-display balsam" id="tree-display">
            <div class="tree-icons">
              <i class="fa fa-tree fa-3x" id="tree-icon">Balsam Fir</i>
            </div>
          </div>
          <h4>Description:</h4>
          <p>Balsam fir is a beautiful pyramidal tree with short, flat, long-lasting, aromatic needles. Balsam fir and Fraser fir have many similar characteristics and some botanists consider them extensions of the same species. Balsam fir has a nice, dark green color and is very fragrant.<br><br></p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class='padding round-border background-white'>
          <%= image_tag 'fraser-fir.jpg', width: '100%' %>
          <br><br>
          <div class="tree-display fraser" id="tree-display">
            <div class="tree-icons">
              <i class="fa fa-tree fa-3x" id="tree-icon">Fraser Fir</i>
            </div>
          </div>
          <h4>Description:</h4>
          <p>The Fraser fir is quickly becoming the most premium species of the cut Christmas tree market. Its mild fragrance, shape, strong limbs, and ability to retain its soft needles for a long time when cut make it one of the best trees for this purpose. It is characterized by a heavy density and is known for its deep hues of blueish green.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/orders/_onetwothree.html.erb
<div class="hidden-xs">
  <div class="row" id="how-content">
    <div class="col-sm-4">
      <span class="fa-stack fa-4x center">
        <i class="fa fa-circle fa-stack-2x green"></i>
        <i class="fa fa-search fa-stack-1x white"></i>
      </span>
      <h3 class='text-center'>Choose your variety</h3>
    </div>
    <div class="col-sm-4">
      <span class="fa-stack fa-4x center">
        <i class="fa fa-circle fa-stack-2x green"></i>
        <i class="fa fa-tree fa-stack-1x white"></i>
      </span>
      <h3 class='text-center'>Order your tree</h3>
      <br>
      <br>
    </div>
    <div class="col-sm-4">
      <span class="fa-stack fa-4x center">
        <i class="fa fa-circle fa-stack-2x green"></i>
        <i class="fa fa-bus fa-stack-1x white"></i>
      </span>
      <h3 class='text-center'>Tree to your door!</h3>
    </div>
  </div>
</div>

<div class="hidden-sm hidden-md hidden-lg">
  <div class="row" id="how-content">
    <div class="col-sm-12">
      <h4>
        <span class="fa-stack fa-2x">
          <i class="fa fa-circle fa-stack-2x green"></i>
          <i class="fa fa-search fa-stack-1x white"></i>
        </span>
        Choose your variety
      </h4>
    </div>
    <div class="col-sm-12">
      <h4>
        <span class="fa-stack fa-2x">
          <i class="fa fa-circle fa-stack-2x green"></i>
          <i class="fa fa-tree fa-stack-1x white"></i>
        </span>
        Order your tree
      </h4>
    </div>
    <div class="col-sm-12">
      <h4>
        <span class="fa-stack fa-2x">
          <i class="fa fa-circle fa-stack-2x green"></i>
          <i class="fa fa-bus fa-stack-1x white"></i>
        </span>
        Tree to your door!
      </h4>
    </div>
  </div>
  <br><br><br>
</div>

app/views/orders/confirm.html.erb
<div class="row" id="top-row">
  <div class="col-md-3 col-sm-2">
  </div>
  <div class='col-md-6 col-sm-8'>
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">Confirm your order</h3>
      </div>
      <div class="panel-body">

        <div class="tree-display <%= @order.tree.type.name.downcase %>" id="tree-display">
          <div class="tree-icons">
            <i class="fa fa-tree fa-3x" id="tree-icon"><%= @order.tree.height.to_s + " ft. " + @order.tree.type.name %></i>
          </div>
        </div>
        <br>
        <h3>Deliver To:</h3>
        <p class="tab">
          <%= @order.name %>
          <br>
          <%= @order.email %>
          <br>
          <%= @order.address %>
          <br>
          <%= @order.city + ", " + @order.state + ", " + @order.zipcode %>
        </p>

      </div>
      <ul class="list-group">
        <% @accessories.each do |a| %>
          <li class="list-group-item">
            <p class="tab">
              <%= a.name %><br>
              <%= a.description %><br>
              <%= "$" + a.price.floor.to_i.to_s %>
            </p>
          </li>
        <% end %>
        <% if @order.instructions.present? %>
          <li class="list-group-item">
            <h4>Instructions:</h4>
            <p class="tab"><%= @order.instructions %></p>
          </li>
        <% end %>
        <li class="list-group-item">
          <h4 class="tab">Tree: <%= @order.tree.height.to_s + "ft. " + @order.tree.type.name + " $" + @order.tree.price.floor.to_i.to_s %></h4>
        </li>
        <li class="list-group-item">
          <h3 class='price-h3'>Total: <%= "$" + @total.floor.to_i.to_s %></h3>
          <div class='text-right'>
            <%= simple_form_for @order, url: orders_path(accessory_orders: @accessories.map { |a| a.id }) do |f| %>
              <%= f.input :tree_id, as: :hidden %>
              <%= f.input :name, as: :hidden %>
              <%= f.input :email, as: :hidden %>
              <%= f.input :phone, as: :hidden %>
              <%= f.input :address, as: :hidden %>
              <%= f.input :city, as: :hidden %>
              <%= f.input :state, as: :hidden %>
              <%= f.input :zipcode, as: :hidden %>
              <%= f.input :window_id, as: :hidden %>
              <%= f.input :instructions, as: :hidden %>
              <%= f.submit 'Confirm', class: 'btn btn-success' %>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
    <br>
  </div>

  <div class="col-md-3 col-sm-2">
  </div>
</div>

<%= render 'onetwothree' %>

<%= render 'balsam_fraser' %>

app/views/orders/index.html.erb
<div class="container">
  <br>
  <div class="row" id="top-row">
    <div class="col-md-3 col-xs-1 col-sm-2">
    </div>
    <div class="col-xs-10 col-sm-8 col-md-6 text-center zip-search white">
      <div class="zip-search-center">
        <h3>Premium Trees Delivered <br>
          To Your Front Door</h3>
        <%= simple_form_for :zipcode_search,  url: zipcode_search_orders_path , method: :get, html: { class: 'form-inline', } do |f| %>
          <%= f.input_field :zipcode,
                      autofocus: true,
                      class: 'form-control',
                      label: false,
                      placeholder: 'Enter your Zip Code!' %>
          <br class="hidden-sm hidden-md hidden-lg">
          <%= f.submit "Submit", class: 'btn btn-success' %>
        <% end %>
        <br>
      </div>
    </div>
    <div class="col-md-3 col-xs-1 col-sm-2">
    </div>
  </div>

  <br>
  <br>
</div>

<%= render "onetwothree" %>

<%= render "balsam_fraser" %>

app/views/orders/new.html.erb
<%= content_tag :div, "", id: 'available_trees', data: { trees: @trees.to_json } %>
<%= content_tag :div, "", id: 'accessories', data: { accessories: @accessories.to_json } %>

<div class="container">
   <div class="row" id='top-row'>
    <div class="col-md-2 col-sm-2 hidden-xs">
    </div>
    <div class="col-md-8 col-sm-8 col-xs-12">
      <br>
      <div class="well">
        <h1>Choose your variety</h1>
        <br>
        <%= simple_form_for @order, url: confirm_orders_path do |f| %>
          <% if @order.errors.any? %>
            <ul>
              <% @order.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          <% end %>

          <div class="form-inputs">
            <%= f.input :tree_id,
                        required: true,
                        collection: @available_trees,
                        selected: @available_trees.first,
                        label: false,
                        input_html: { class: 'form-control'} %>
                        <br>
            <div class="tree-display display-none" id="tree-display">
              <div class="tree-icons">
                <i class="fa fa-tree fa-3x" id="tree-icon"></i>
              </div>
            </div>
            <br>
            <%= f.input :name,
                        required: true,
                        label: false,
                        placeholder: 'Full Name (required)',
                        input_html: { class: 'form-control'} %>
                        <br>
            <div class="row">
              <div class="col-md-6 col-sm-6 col-xs-6">
                <%= f.input :email,
                            required: true,
                            label: false,
                            placeholder: 'Email (required)',
                            input_html: { class: 'form-control'} %>
                            <br>
              </div>

              <div class="col-md-6 col-sm-6 col-xs-6">
                <%= f.input :phone,
                            required: true,
                            label: false,
                            placeholder: 'Phone Number with area code (required)',
                            input_html: { class: 'form-control'} %>
                            <br>
              </div>
            </div>
            <%= f.input :address,
                        required: true,
                        label: false,
                        placeholder: 'Address (required)',
                        input_html: { class: 'form-control'} %>
                        <br>
            <div class="row">
              <div class="col-md-6 col-sm-5 col-xs-5">
                  <% if @city.nil? %>
                    <%= f.input :city,
                                required: true,
                                label: false,
                                placeholder: 'City (required)',
                                input_html: { class: 'form-control'} %>
                                <br>
                  <% else %>
                    <%= f.input :city,
                                required: true,
                                label: false,
                                readonly: true,
                                input_html: { class: 'form-control', value: @city} %>
                                <br>
                  <% end %>
              </div>
              <div class="col-md-2 col-sm-3 col-xs-3">
                  <% if @state.nil? %>
                    <%= f.input :state,
                                required: true,
                                label: false,
                                placeholder: 'State (required)',
                                input_html: { class: 'form-control'} %>
                                <br>
                  <% else %>
                    <%= f.input :state,
                                required: true,
                                label: false,
                                readonly: true,
                                input_html: { class: 'form-control', value: @state} %>
                                <br>
                  <% end %>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-4">
                <%= f.input :zipcode,
                            required: true,
                            readonly: true,
                            label: false,
                            input_html: { class: 'form-control', value: @zip} %>
                            <br>
              </div>
            </div>
            <%= f.input :accessory_orders,
                        multiple: true,
                        label: 'Available Accessories',
                        collection: @accessories,
                        label_method: Proc.new { |a| "$" + a.price.to_i.to_s + " " + a.name + ": " + a.description},
                        as: :check_boxes,
                        checked: params[:accessory_orders],
                        input_html: { class: 'accessories' } %>
                        <br>
            <h3>When would you like your tree delivered?</h3>
            <%= f.input :window_id,
                        required: true,
                        label: false,
                        collection: @windows,
                        selected: @windows.first,
                        label_method: :delivery_window,
                        input_html: { class: 'form-control'} %>
                        <br>
            <%= f.input :instructions,
                        placeholder: 'Special Delivery Instructions',
                        label: false,
                        input_html: { class: 'form-control' } %>
                        <br>
          </div>

          <h3 id='price'>Total: </h3>
          <br>

          <div class="form-actions">
            <%= f.button :submit, "Submit Order!", class: "btn btn-lg btn-block btn-success" %>
          </div>
        <% end %>
      </div>
      <br>
    </div>
    <div class="col-md-2 col-sm-2 hidden-xs">
    </div>
  </div>
</div>

<%= render "onetwothree" %>

<%= render "balsam_fraser" %>

app/views/orders/order_confirmation.html.erb
<div class="row" id="top-row">
  <div class="col-md-3 col-sm-2">
  </div>
  <div class='col-md-6 col-sm-8'>
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">Order Processed!</h3>
      </div>
      <div class="panel-body">

        <div class="tree-display <%= @order.tree.type.name.downcase %>" id="tree-display">
          <div class="tree-icons">
            <i class="fa fa-tree fa-3x" id="tree-icon"><%= @order.tree.height.to_s + " ft. " + @order.tree.type.name %></i>
          </div>
        </div>

      </div>
      <ul class="list-group">
        <li class="list-group-item">
          <h3><i class="fa fa-tree"></i> What now?</h3>
          <h5 class="tab">You will be called within 24 hours to set up delivery</h5>
          <h3><i class="fa fa-tree"></i> How do I pay?</h3>
          <h5 class="tab">Pay by cash on delivery</h5>
        </li>
        <li class="list-group-item">
          <br>
          <h3>Deliver To:</h3>
          <p class="tab">
            <%= @order.name %>
            <br>
            <%= @order.email %>
            <br>
            <%= @order.address %>
            <br>
            <%= @order.city + ", " + @order.state + ", " + @order.zipcode %>
          </p>
          <% @accessories.each do |a| %>
            <p class="tab">
              <strong><%= a.name %></strong><br>
              <%= a.description %><br>
              <%= "$" + a.price.floor.to_i.to_s %>
            </p>
          <% end %>
          <% if @order.instructions.present? %>
            <h4>Instructions:</h4>
            <p class="tab"><%= @order.instructions %></p>
          <% end %>
          <h4 class="tab">Tree: <%= @order.tree.height.to_s + "ft. " + @order.tree.type.name + " $" + @order.tree.price.floor.to_i.to_s %></h4>
        </li>
        <li class="list-group-item">
          <h3 class='price-h3'>Total: <%= "$" + @total.floor.to_i.to_s %></h3>
        </li>
      </ul>
    </div>
    <br>
  </div>

  <div class="col-md-3 col-sm-2">
  </div>
</div>

<%= render 'onetwothree' %>

<%= render 'balsam_fraser' %>

app/views/orders/show.html.erb
<div class="row" id="top-row">
  <div class="col-md-3 col-sm-2">
  </div>
  <div class='col-md-6 col-sm-8'>
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">Order</h3>
      </div>
      <div class="panel-body">

        <div class="tree-display <%= @order.tree.type.name.downcase %>" id="tree-display">
          <div class="tree-icons">
            <i class="fa fa-tree fa-3x" id="tree-icon"><%= @order.tree.height.to_s + " ft. " + @order.tree.type.name %></i>
          </div>
        </div>

      </div>
      <ul class="list-group">
        <li class="list-group-item">
          <br>
          <h3>Deliver To:</h3>
          <p class="tab">
            <%= @order.name %>
            <br>
            <%= @order.email %>
            <br>
            <%= @order.phone %>
            <br>
            <%= @order.address %>
            <br>
            <%= @order.city + ", " + @order.state + ", " + @order.zipcode %>
          </p>
          <% @accessories.each do |a| %>
            <p class="tab">
              <strong><%= a.name %></strong><br>
              <%= a.description %><br>
              <%= "$" + a.price.floor.to_i.to_s %>
            </p>
          <% end %>
          <% if @order.instructions.present? %>
            <h4>Instructions:</h4>
            <p class="tab"><%= @order.instructions %></p>
          <% end %>
          <h4 class="tab">Tree: <%= @order.tree.height.to_s + "ft. " + @order.tree.type.name + " $" + @order.tree.price.floor.to_i.to_s %></h4>
        </li>
        <li class="list-group-item">
          <h3 class='price-h3'>Total: <%= "$" + @total.floor.to_i.to_s %></h3>
        </li>
      </ul>
    </div>
    <br>
  </div>

  <div class="col-md-3 col-sm-2">
  </div>
</div>