config/routes.rb
Rails.application.routes.draw do
  devise_for :lots
  root 'orders#index'

  resources :lots do
    collection do
      get 'open_orders'
    end
  end
  resources :contacts do
    collection do
      post 'read'
      post 'unread'
      get 'faq'
    end
  end
  resources :accessories
  resources :zips
  resources :trees
  resources :available_trees
  resources :orders do
    collection do
      get 'zipcode_search'
      get 'order_confirmation'
      post 'order_claim'
      post 'order_release'
      post 'order_delivered'
      post 'confirm'
    end
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :message
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :authenticate_lot!, except: [:faq]

  def index
    @contacts = Contact.where(read: false)
    @read = Contact.where(read: true)
  end

  def create
    @contact = Contact.new(contacts_params)

    if @contact.save
      render json: @contact
    else
      render json: { errors: @contact.errors.full_messages }, :status => 422
    end
  end

  def read
    @contact = Contact.find(params[:id])

    if @contact.update_attributes(read: true)
      flash[:notice] = 'Messaged Updated!'
      redirect_to contacts_path
    else
      flash[:notice] = 'Message update failed!'
      redirect_to contacts_path
    end
  end

  def unread
    @contact = Contact.find(params[:id])

    if @contact.update_attributes(read: false)
      flash[:notice] = 'Messaged Updated!'
      redirect_to contacts_path
    else
      flash[:notice] = 'Message update failed!'
      redirect_to contacts_path
    end
  end

  def contacts_params
    params.require(:contact).permit(:name, :email, :phone, :message)
  end
end

app/views/contacts/faq.html.erb
<div class="row" id="top-row">
  <div class="col-md-3 col-xs-1 col-sm-2">
  </div>
  <div class="col-xs-10 col-sm-8 col-md-6 text-center zip-search white">
    <div class="zip-search-center">
      <h3>Premium Trees Delivered <br>
        To Your Front Door</h3>
      <%= simple_form_for :zipcode_search,  url: zipcode_search_orders_path , method: :get, html: { class: 'form-inline', } do |f| %>
        <%= f.input_field :zipcode,
                    autofocus: true,
                    class: 'form-control',
                    label: false,
                    placeholder: 'Enter your Zip Code!' %>
        <br class="hidden-sm hidden-md hidden-lg">
        <%= f.submit "Submit", class: 'btn btn-success' %>
      <% end %>
      <br>
    </div>
  </div>
  <div class="col-md-3 col-xs-1 col-sm-2">
  </div>
</div>
<div class="row">
  <br>
  <br>
  <div class="container">
    <div class="row row-padding-top">
      <div class="col-xs-12 col-sm-6">
        <div class='faq-bubble'>
          <div class="alert alert-success">
            <p>How do I know I'll get a nice tree?</p>
          </div>
          <div class='faq-padding'>
            <p>Good question! Christmas trees are purchased from tree farmer's based on three grades. They are premium grade, #1 grade and #2 grade. Premium grade trees are the "cream of the crop". They are guaranteed to be the best tree's the farmer has grown for that given year. We ONLY purchase and deliver premium grade tree's.</p>
          </div>
        </div>

        <div class='faq-bubble'>
          <div class="alert alert-success">
            <p>Why buy a tree from us?</p>
          </div>
          <div class='faq-padding'>
            <p>Because it's completely hassle free!  We deliver farm grown, freshly cut, premium grade trees directly to your front door! Awesome right?</p>
          </div>
        </div>

        <div class='faq-bubble'>
          <div class="alert alert-success">
            <p>What is the difference between Frasier fir and Balsam fir?</p>
          </div>
          <div class='faq-padding'>
            <p>The Balsam fir is a beautiful pyramidal tree with short, flat, long-lasting, aromatic needles. It is characterized by a nice, dark green color and is very fragrant.</p>

            <p>The Fraser fir is quickly becoming the most premium species of the cut Christmas tree market. Its mild fragrance, shape, strong limbs, and ability to retain its soft needles for a long time when cut make it one of the best trees for this purpose. It is characterized by a heavy density and is known for its deep hues of blueish green.</p>
          </div>
        </div>

        <div class='faq-bubble'>
          <div class="alert alert-success">
            <p>Will the tree shed?</p>
          </div>
          <div class='faq-padding'>
            <p>It's only natural that most trees will shed some needles in the weeks leading up to Christmas Day. Since all of our trees are premium grade and cut very close to Thanksgiving, If they're given proper water and kept at a reasonable distance from heat sources, there should be minimal shedding.</p>
          </div>
        </div>
      </div>

      <div class="col-xs-12 col-sm-6">
        <div class='faq-bubble'>
          <div class="alert alert-success">
            <p>How should I best care for my tree?</p>
          </div>
          <div class='faq-padding'>
            <p>Add water to your stand immediately when you bring your tree into the house. Keep as far away as possible from heat sources. Check daily to make sure the water does not go below the base of the tree.</p>
          </div>
        </div>

        <div class='faq-bubble'>
          <div class="alert alert-success">
            <p>Do you give it a fresh cut prior to delivery?</p>
          </div>
          <div class='faq-padding'>
            <p>Yes. All of our trees are given a fresh cut immediately before being delivered to your home.</p>
          </div>
        </div>

        <div class='faq-bubble'>
          <div class="alert alert-success">
            <p>How fast will my tree arrive after I submit my order?</p>
          </div>
          <div class='faq-padding'>
            <p>One of the Christmas Tree Guys will contact you within 24 hours of your order to schedule a delivery date/time. Immediately following Thanksgiving we will be delivering on a daily basis. We will do our best to coordinate with you to get your tree delivered in the timeliest manner possible.</p>
          </div>
        </div>

        <div class='faq-bubble'>
          <div class="alert alert-success">
            <p>Where do the trees come from?</p>
          </div>
          <div class='faq-padding'>
            <p>Our Balsam Firs are fresh cut from farms in Maine and New Hampshire while our Fraser Firs our fresh cut from farms in North Carolina.</p>
          </div>
        </div>

        <div class='faq-bubble'>
          <div class="alert alert-success">
            <p>Do you deliver to apartment complexes and businesses as well as single family homes?</p>
          </div>
          <div class='faq-padding'>
            <p>Yes. We will deliver to anyone within our delivery radiuses.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
  <br>
</div>

app/views/contacts/index.html.erb
<div class='row'>
  <div class='col-md-12'>
    <br>
    <div class='panel panel-tree'>
      <div class="panel-heading">Messages</div>
      <div class='panel-body'>
        <div>
          <table class="table">
              <thead>
                <tr>
                  <th>Submitted</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Phone</th>
                  <th>Message</th>
                  <th class="text-right">Read?</th>
                </tr>
              </thead>
              <tbody>
              <% @contacts.each_with_index do |c, index| %>
                <tr>
                  <td><%= c.created_at.to_date.strftime('%m/%d/%y') %></td>
                  <td><%= c.name %></td>
                  <td><%= c.email %></td>
                  <td><%= c.phone %></td>
                  <td><%= c.message %></td>
                  <td class="text-right">
                    <%= link_to read_contacts_path(id: c.id), data: { confirm: "Are you sure?" }, method: :post, class: 'btn btn-success' do %>
                      <i class="fa fa-check"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<div class='row'>
  <div class='col-md-12'>
    <br>
    <div class='panel panel-tree'>
      <div class="panel-heading">Read Messages</div>
      <div class='panel-body'>
        <div>
          <table class="table">
            <thead>
              <tr>
                <th>Submitted</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Message</th>
                <th class="text-right">Mark Unread?</th>
              </tr>
            </thead>
            <tbody>
              <% @read.each_with_index do |c, index| %>
                <tr>
                  <td><%= c.created_at.to_date.strftime('%m/%d/%y') %></td>
                  <td><%= c.name %></td>
                  <td><%= c.email %></td>
                  <td><%= c.phone %></td>
                  <td><%= c.message %></td>
                  <td class="text-right">
                    <%= link_to unread_contacts_path(id: c.id), data: { confirm: "Are you sure?" }, method: :post, class: 'btn btn-primary' do %>
                      <i class="fa fa-check"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>