config/routes.rb
Rails.application.routes.draw do
  devise_for :lots
  root 'orders#index'

  resources :lots do
    collection do
      get 'open_orders'
    end
  end
  resources :contacts do
    collection do
      post 'read'
      post 'unread'
      get 'faq'
    end
  end
  resources :accessories
  resources :zips
  resources :trees
  resources :available_trees
  resources :orders do
    collection do
      get 'zipcode_search'
      get 'order_confirmation'
      post 'order_claim'
      post 'order_release'
      post 'order_delivered'
      post 'confirm'
    end
  end
end

app/models/lot.rb
class Lot < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, uniqueness: true
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :first_name
  validates_presence_of :last_name

  has_many :available_trees
  has_many :zips
end

app/controllers/lot_controller.rb
class LotsController < ApplicationController

end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
  before_filter :authenticate_lot!

  def index
    @lots = Lot.all
  end

  def show
    @lot = Lot.find(params[:id])
    @new_zip = Zip.new
    @delivery_zipcodes = Zip.where(lot_id: @lot.id)
    @orders = Order.where(lot_id: @lot.id, delivered: false)
    @delivered = Order.where(lot_id: @lot.id, delivered: true)
    @trees = Tree.all.includes(:type)
    @available_trees = @lot.available_trees
    @new_tree = AvailableTree.new
  end

  def open_orders
    @orders = Order.where(lot_id: nil)
  end
end

app/views/lots/open_orders.html.erb
<div class="row" id="top-row">
  <div class="col-xs-1">
  </div>
  <div class="col-xs-10 well">
    <h3>Unclaimed Orders!</h3>
    <table class="table table-striped table-responsive">
      <thead>
        <tr>
          <th></th>
          <th>Name</th>
          <th>Address</th>
          <th>City, State, Zipcode</th>
          <th>Tree</th>
          <th>Delivery Selection</th>
          <th>Claim!</th>
        </tr>
      </thead>
      <% @orders.each_with_index do |order, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= order.name %></td>
          <td><%= order.address %></td>
          <td><%= order.city + ", " + order.state + " " + order.zipcode %></td>
          <td><%= order.tree.nil? ? 'tree nil order id: ' + order.id.to_s : order.tree.height.to_s + " ft. " + order.tree.type.name %></td>
          <td><%= order.window.delivery_window %></td>
          <td>
            <%= link_to order_path(id: order.id, order_id: order.id), class: 'btn btn-warning' do %>
              <i class="fa fa-search "></i>
            <% end %>
            <%= link_to order_claim_orders_path(order_id: order.id), method: :post, class: 'btn btn-success' do %>
              <i class="fa fa-star "></i>
            <% end %>
          </td>
          <% order.accessories.each do |a| %>
            <tr>
              <td></td>
              <td></td>
              <td>+Accessory</td>
              <td><%= a.name %></td>
              <td>$<%= a.price %></td>
              <td></td>
              <td></td>
            </tr>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="col-xs-1">
  </div>
</div>

app/views/lots/show.html.erb
<div class='row' id='top-row'>
  <div class='col-md-12'>
    <br>
    <div class='panel panel-tree'>
      <div class="panel-heading">Your Orders</div>
      <div class='panel-body'>
        <% if @orders.empty? %>
          <p>You dont have any orders to deliver! <%= link_to 'Claim orders!', open_orders_lots_path %></p>
        <% else %>
          <div style='overflow: auto; max-height: 350px;'>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th></th>
                  <th>Name</th>
                  <th>Address</th>
                  <th>Tree</th>
                  <th>Delivery Window</th>
                  <th class='text-right'>Delivered/Release?</th>
                </tr>
              </thead>
              <% @orders.each_with_index do |order, index| %>
                <tr>
                  <td><%= index + 1 %></td>
                  <td><%= order.name %></td>
                  <td><%= order.address + ", " + order.city + ", " + order.state + " " + order.zipcode %></td>
                  <td><%= order.tree.nil? ? 'deleted' : order.tree.height.to_s + " ft. " + order.tree.type.name %></td>
                  <td><%= order.window.delivery_window if order.window.present? %></td>
                  <td class='text-right'>
                    <%= link_to order_path(order_id: order.id), class: 'btn btn-warning' do %>
                      <i class="fa fa-search "></i>
                    <% end %>
                    <%= link_to order_delivered_orders_path(order_id: order.id), method: :post, class: 'btn btn-success' do %>
                      <i class="fa fa-tree "></i>
                    <% end %>
                    <%= link_to order_release_orders_path(order_id: order.id), data: { confirm: "Are you sure?" }, method: :post, class: 'btn btn-danger' do %>
                      <i class="fa fa-remove "></i>
                    <% end %>
                  </td>
                </tr>
                <% order.accessories.each do |a| %>
                  <tr>
                    <td></td>
                    <td></td>
                    <td>+Accessory</td>
                    <td><%= a.name %></td>
                    <td>$<%= a.price %></td>
                    <td></td>
                  </tr>
                <% end %>
              <% end %>
            </table>
          </div>
          <%= link_to 'Claim more orders!', open_orders_lots_path, class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if !@delivered.empty? %>
  <div class='row'>
    <div class='col-md-12'>
      <br>
      <div class='panel panel-tree'>
        <div class="panel-heading">Delivered Orders</div>
        <div class='panel-body'>
          <div style='overflow: auto; max-height: 350px;'>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th></th>
                  <th>Name</th>
                  <th>Address</th>
                  <th>Tree</th>
                  <th>Delivery Window</th>
                  <th class='text-right'>Delivered/Release?</th>
                </tr>
              </thead>
              <% @delivered.each_with_index do |order, index| %>
                <tr>
                  <td><%= index + 1 %></td>
                  <td><%= order.name %></td>
                  <td><%= order.address + ", " + order.city + ", " + order.state + " " + order.zipcode %></td>
                  <td><%= order.tree.nil? ? 'deleted' : order.tree.height.to_s + " ft. " + order.tree.type.name %></td>
                  <td><%= order.window.delivery_window if order.window.present? %></td>
                  <td class='text-right'>
                  </td>
                </tr>
                <% order.accessories.each do |a| %>
                  <tr>
                    <td></td>
                    <td></td>
                    <td>+Accessory</td>
                    <td><%= a.name %></td>
                    <td>$<%= a.price %></td>
                    <td></td>
                  </tr>
                <% end %>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class='row'>
  <div class='col-md-8'>
    <div class='panel panel-tree'>
      <div class="panel-heading">Available Trees</div>
      <div class='panel-body'>
        <div>
          <table class="table">
            <thead>
              <tr>
                <th></th>
                <th>Type</th>
                <th>Height</th>
                <th>Price</th>
                <th class="text-right"></th>
              </tr>
            </thead>
            <% @trees.each_with_index do |tree, index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= tree.type.name %></td>
                <td><%= tree.height %></td>
                <td><%= "$" + tree.price.to_s %></td>
                <% if @available_trees.map(&:tree_id).include?(tree.id) %>
                  <td class="text-right">
                    <%= simple_form_for @new_tree do |f| %>
                      <%= f.input :tree_id,
                        as: :hidden,
                        input_html: { value: tree.id}
                        %>
                      <%= f.input :lot_id,
                        as: :hidden,
                        input_html: { value: @lot.id}
                        %>
                      <%= f.submit value: 'Available', disabled: true, class: 'btn btn-success left'%>
                    <% end %>
                    <%= link_to 'Unavailable', available_tree_path(tree, lot_id: @lot.id), method: :delete, class: 'btn btn-default'%>
                  </td>
                <% else %>
                  <td class="text-right">
                    <%= simple_form_for @new_tree do |f| %>
                      <%= f.input :tree_id,
                        as: :hidden,
                        input_html: { value: tree.id}
                        %>
                      <%= f.input :lot_id,
                        as: :hidden,
                        input_html: { value: @lot.id}
                        %>
                      <%= f.submit value: 'Available', class: 'btn btn-default left'%>
                    <% end %>
                    <%= link_to 'Unavailable', available_tree_path(tree, lot_id: @lot.id), method: :delete, disabled: true, class: 'btn btn-danger'%>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>

  <div class='col-md-4'>
    <div class='panel panel-tree'>
      <div class="panel-heading">Zipcodes served</div>
      <div class='panel-body'>
        <% if @delivery_zipcodes.empty? %>
          <p>Add a zipcode and start recieving orders!</p>
        <% end %>
        <div style='overflow: auto; max-height: 350px;'>
          <table class="table table-striped">
            <thead>
              <tr>
                <th></th>
                <th>Zipcode</th>
                <th class="text-right">Remove?</th>
              </tr>
            </thead>
            <% @delivery_zipcodes.each_with_index do |zip, index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= zip.code %></td>
                <td class="text-right">
                  <%= link_to zip_path(zip), data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-danger' do %>
                    <i class="fa fa-trash-o "></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </table>
        </div>
        <%= simple_form_for @new_zip do |f| %>
          <%= f.input :code,
                      input_html: { class: 'form-control'},
                      label: false,
                      placeholder: 'Add a zipcode' %>
          <%= f.input :lot_id,
                      as: :hidden,
                      input_html: { value: @lot.id}
                      %>
          <br>
          <%= f.submit "Submit", class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
</div>