config/routes.rb
Rails.application.routes.draw do
  devise_for :lots
  root 'orders#index'

  resources :lots do
    collection do
      get 'open_orders'
    end
  end
  resources :contacts do
    collection do
      post 'read'
      post 'unread'
      get 'faq'
    end
  end
  resources :accessories
  resources :zips
  resources :trees
  resources :available_trees
  resources :orders do
    collection do
      get 'zipcode_search'
      get 'order_confirmation'
      post 'order_claim'
      post 'order_release'
      post 'order_delivered'
      post 'confirm'
    end
  end
end

app/views/layouts/_contact.html.erb
<div class="modal fade" id="contact" tabindex="-1" role="dialog" aria-labelledby="contactLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h3 class="modal-title" id="contactLabel">We want to hear from you!</h3>
      </div>
      <div class='row'>
        <div class='col-md-1 col-sm-1 hidden-xs'></div>
        <div class='col-md-10 col-sm-10 col-xs-12'>
          <div class="modal-body" id='modal-body'>
            <h3>Hassle Free Trees</h3>
            <p class="tab"><strong>Phone:</strong> +1-978-766-5866<br>
               <strong>Email:</strong> <%= mail_to 'thechristmastreeguys1@gmail.com' %></p><br>

            <%= simple_form_for Contact.new, method: :post, remote: true, html: { id: :contacts } do |f| %>
              <%= f.input :name,
                          required: true,
                          label: false,
                          placeholder: 'Name',
                          input_html: { class: 'form-control'} %>
                          <br>
              <%= f.input :email,
                          required: true,
                          label: false,
                          placeholder: 'Email',
                          input_html: { class: 'form-control'} %>
                          <br>
              <%= f.input :phone,
                          label: false,
                          placeholder: 'Phone (optional)',
                          input_html: { class: 'form-control'} %>
                          <br>
              <%= f.input :message,
                          required: true,
                          label: false,
                          placeholder: 'add a message',
                          input_html: { class: 'form-control'} %>
                          <br>
            </div>
          </div>
        </div>
        <div class='col-md-1 col-sm-1 hidden-xs'></div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit 'Send!', class: 'btn btn-success' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_faq.html.erb
<div class="row background-light-green" id="faq">
  <div class="container">
    <div class="row white row-padding-top">
      <div class="col-xs-12 col-sm-6">
        <div class='faq-bubble'>
          <div class="alert alert-success">
            <p>How do I know I'll get a nice tree?</p>
          </div>
          <div class='faq-padding'>
            <p>Good question! Christmas trees are purchased from tree farmer's based on three grades. They are premium grade, #1 grade and #2 grade. Premium grade trees are the "cream of the crop". They are guaranteed to be the best tree's the farmer has grown for that given year. We ONLY purchase and deliver premium grade tree's.</p>
          </div>
        </div>

        <div class='faq-bubble'>
          <div class="alert alert-success">
            <p>Why buy a tree from us?</p>
          </div>
          <div class='faq-padding'>
            <p>Because it's completely hassle free!  We deliver farm grown, freshly cut, premium grade trees directly to your front door! Awesome right?</p>
          </div>
        </div>

        <div class='faq-bubble'>
          <div class="alert alert-success">
            <p>What is the difference between Frasier fir and Balsam fir?</p>
          </div>
          <div class='faq-padding'>
            <p>The Balsam fir is a beautiful pyramidal tree with short, flat, long-lasting, aromatic needles. It is characterized by a nice, dark green color and is very fragrant.

            The Fraser fir is quickly becoming the most premium species of the cut Christmas tree market. Its mild fragrance, shape, strong limbs, and ability to retain its soft needles for a long time when cut make it one of the best trees for this purpose. It is characterized by a heavy density and is known for its deep hues of blueish green.</p>
          </div>
        </div>

        <div class='faq-bubble'>
          <div class="alert alert-success">
            <p>Will the tree shed?</p>
          </div>
          <div class='faq-padding'>
            <p>It's only natural that most trees will shed some needles in the weeks leading up to Christmas Day. Since all of our trees are premium grade and cut very close to Thanksgiving, If they're given proper water and kept at a reasonable distance from heat sources, there should be minimal shedding.</p>
          </div>
        </div>
      </div>

      <div class="col-xs-12 col-sm-6">
        <div class='faq-bubble'>
          <div class="alert alert-success">
            <p>How should I best care for my tree?</p>
          </div>
          <div class='faq-padding'>
            <p>Add water to your stand immediately when you bring your tree into the house. Keep as far away as possible from heat sources. Check daily to make sure the water does not go below the base of the tree.</p>
          </div>
        </div>

        <div class='faq-bubble'>
          <div class="alert alert-success">
            <p>Do you give it a fresh cut prior to delivery?</p>
          </div>
          <div class='faq-padding'>
            <p>Yes. All of our trees are given a fresh cut immediately before being delivered to your home.</p>
          </div>
        </div>

        <div class='faq-bubble'>
          <div class="alert alert-success">
            <p>How fast will my tree arrive after I submit my order?</p>
          </div>
          <div class='faq-padding'>
            <p>One of the Christmas Tree Guys will contact you within 24 hours of your order to schedule a delivery date/time. Immediately following Thanksgiving we will be delivering on a daily basis. We will do our best to coordinate with you to get your tree delivered in the timeliest manner possible.</p>
          </div>
        </div>

        <div class='faq-bubble'>
          <div class="alert alert-success">
            <p>Where do the trees come from?</p>
          </div>
          <div class='faq-padding'>
            <p>Our Balsam Firs are fresh cut from farms in Maine and New Hampshire while our Fraser Firs our fresh cut from farms in North Carolina.</p>
          </div>
        </div>

        <div class='faq-bubble'>
          <div class="alert alert-success">
            <p>Do you deliver to apartment complexes and businesses as well as single family homes?</p>
          </div>
          <div class='faq-padding'>
            <p>Yes. We will deliver to anyone within our delivery radiuses.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="background-grey footer site-footer" id="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4">
      </div>

      <div class="hidden-xs">
        <div class="col-xs-12 col-sm-4">
          <br>
          <span class="fa-stack fa-5x center">
            <i class="fa fa-circle fa-stack-2x light-grey"></i>
            <i class="fa fa-tree fa-stack-1x grey"></i>
          </span>
          <br>
        </div>
      </div>

      <div class="hidden-sm hidden-md hidden-lg">
        <div class="col-xs-12 col-sm-4">
          <br>
          <span class="fa-stack fa-4x center">
            <i class="fa fa-circle fa-stack-2x light-grey"></i>
            <i class="fa fa-tree fa-stack-1x grey"></i>
          </span>
          <br>
        </div>
      </div>

      <div class="col-xs-12 col-sm-4">
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hassle Free Trees - Tree Delivery</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
<body class="trees-bg">
  <div class='page-wrap'>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: 'navbar-brand' do %>
            <i class="fa fa-tree"> Hassle Free Trees</i>
          <% end %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_lot.present? %>
              <li><%= link_to current_lot.name, lot_path(current_lot) %></li>
              <li>
                <%= link_to open_orders_lots_path do %>
                  <%= 'Claim Orders! (' + Order.where(lot_id: nil).count.to_s + ')' %>
                <% end %>
              </li>
              <li><%= link_to 'Trees', trees_path %></li>
              <li><%= link_to 'Accessories', accessories_path %></li>
              <li>
                <%= link_to contacts_path do %>
                  <%= 'Messages (' + @contacts = Contact.where(read: false).count.to_s + ')' %>
                <% end %>
              </li>
              <li><%= link_to 'Logout', destroy_lot_session_path, method: :delete %></li>
            <% else %>
              <li><a href="#" data-toggle="modal" data-target="#contact">Contact Us</a></li>
              <li><%= link_to 'FAQ', faq_contacts_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-12">
         <div id="notice-box">
           <% if flash[:notice] %>
            <div class="alert alert-success">
              <%= flash[:notice] %>
            </div>
          <% end %>
        </div>

          <%= yield %>

        </div>
      </div>
    </div>
  </div>

  <%= render partial: 'layouts/footer' %>

  <%= render partial: 'layouts/contact' %>

  <script>
    var top_row = 180 + $('#top-row').height();
    var css = '100% ' + top_row + 'px';
    if (top_row < 380) {
      css = '100% 380px';
    } else if (top_row > 600) {
      css = '100% 600px';
    };
    $('.trees-bg').css('background-size', css);
  </script>
</body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-57227947-1', 'auto');
  ga('send', 'pageview');

</script>
</html>